spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
  application:
    name: vs
  h2:
   console:
    enabled: true
    path: /h2
  datasource:
   url: jdbc:h2:~/test3_db 
  jpa:
   hibernate:
    ddl-auto:update
  
eureka:
  client:
    enabled: false
dekorate:
  kubernetes:
    serviceType: "NodePort"

server:
  port: 8084